### ISSUE TITLE
Logo is rendering weird

### ISSUE THREAD

**Issue by salkinium** [roboterclubaachen/xpcc.io#3]
Rendering wrongly both in Safari and Chrome:
<img width="240" src="https://cloud.githubusercontent.com/assets/163066/19271683/997648c2-8fbd-11e6-823a-f60f7f1842d3.png">

**Comment by salkinium** [comment]
I suspect that's because the font that the SVG uses is not available on the system.

cc @dergraaf

**Comment by dergraaf** [comment]
It should be possible to convert the text into a vector, this might solve the problem. I can look into that in the next days.

**Comment by dergraaf** [comment]
Might be fixed with ccf4e72b40a66ad3539ce82fe52469ab1e859e20. I had the same rendering issue on my Debian VM until I install the Ubuntu font.

**Comment by salkinium** [comment]
Renders correctly on computers without Ubuntu font installed. Thanks!
